- name: Set clock format in menu bar
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: 'EEE MMM d  H:mm:ss'
    state: present

- name: Use scale effect for minimizing windows to dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: scale
    state: present

- name: Display full POSIX path in Finder window title
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
    state: present

- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: string
    value: true
    state: present

- name: Make Dock icons of hidden applications translucent
  community.general.osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true

- name: Show all file extensions
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Show status bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

- name: Show path bar in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

- name: Enable text selection in Quick Look
  community.general.osx_defaults:
    domain: com.apple.finder
    key: QLEnableTextSelection
    type: bool
    value: true

- name: Show folders on top when sorting by name in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true

- name: Set default search scope to current folder in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"

- name: Disable the warning when changing a file extension in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false

- name: Don't write .DS_Store files to network shares
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Don't write .DS_Store files to USB drives
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: Disable the warning before emptying the Trash
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false

- name: Show indicator lights for open applications in the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true

- name: Don't show recently used applications in the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false

- name: Show the main window when launching Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true

- name: Visualize CPU usage in the Activity Monitor Dock icon
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: int
    value: 5

- name: Show all processes in Activity Monitor
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0

- name: Set Activity Monitor sort column to CPU usage
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "CPUUsage"

- name: Set Activity Monitor sort direction
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: 0

- name: Three finger drag
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerDrag
    type: bool
    value: true

- name: Enable tap to click (Trackpad) 1
  community.general.osx_defaults:
    domain: com.apple.driver.AppleMultitouchTrackpad
    key: Clicking
    type: bool
    value: true

- name: Enable tap to click (Trackpad) 2
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: true

- name: Kill affected applications
  command: killall "{{ item }}"
  with_items:
    - Finder
    - Dock
    - SystemUIServer
