- name: Dev setup
  hosts: localhost
  tasks:
    - name: brew
      ansible.builtin.include_tasks:
        file: ./brew.yaml
        apply:
          tags: install, brew
      tags: brew
    - name: macos defaults
      ansible.builtin.include_tasks:
        file: ./defaults.yaml
        apply:
          tags: install, defaults
      tags: defaults
    - name: config links
      ansible.builtin.include_tasks:
        file: ./links.yaml
        apply:
          tags: install, links
      tags: links
